directory: /mnt/data/music
library: /mnt/data/music/.library.db
original_date: yes
plugins: convert embedart fetchart ftintitle lastgenre scrub zero
threaded: yes
timeout: 5.0
verbose: no

ui:
    color: yes

import:
    move: yes

bandcamp:
    art: yes

embedart:
    remove_art_file: yes

fetchart:
    cover_names: cover front
    sources:
        - bandcamp
        - filesystem
        - itunes
        - lastfm
        - amazon
        - fanarttv

zero:
  fields: month day comments
  update_database: true

paths:
    default: $albumartist/$year - $album/$track. $title
