directory: /mnt/data/music
library: /mnt/data/music/.library.db
original_date: yes
plugins: convert fetchart ftintitle lastgenre scrub zero
threaded: yes
timeout: 5.0
verbose: no

ui:
    color: yes

import:
    move: yes

bandcamp:
    art: yes

convert:
    auto: yes
    never_convert_lossy_files: yes
    ffmpeg: /usr/bin/ffmpeg
    opts: -ab 320k -ac 2 -ar 48000
    max_bitrate: 320

fetchart:
    cover_names: cover front
    sources:
        - bandcamp
        - filesystem
        - itunes
        - lastfm
        - amazon
        - fanarttv

zero:
  fields: month day comments images
  update_database: true

paths:
    default: $albumartist/$year - $album/$track. $title
