directory: ~/Music
library: ~/Music/.library.db
original_date: yes
plugins: convert embedart deezer fetchart ftintitle lastgenre scrub zero

#use multiple threads
threaded: yes
timeout: 5.0
verbose: no

ui:
    color: yes

import:
    move: yes

convert:
    auto: yes
    embed: no
    never_convert_lossy_files: yes
    formats:
        mp3: ffmpeg -i $source -y -ab 320k $dest

embedart:
    remove_art_file: yes

fetchart:
    cover_names: cover front
    sources:
        - filesystem
        - itunes
        - lastfm
        - amazon
        - fanarttv

ftintitle:
    drop: yes

zero:
  fields: month day

paths:
    default: $albumartist/$year - $album/$track. $title
